version: "3.3"
services:
    mongo-db:
        image: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root_password

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root_password
            ME_CONFIG_MONGODB_SERVER: mongo-db

    gobook-server:
        build: ../build/package/Dockerfile
        ports:
            - 8080:8080
        depends_on:
            - mongo-db
        environment:
            MONGO_CONNECTION_STRING: "mongodb://root:root_password@mongo-db:27017"
